import React from "react";
import FactNumber from "../components/AboutComponents.jsx/FactNumber";

const About = () => {
  return (
    <>
      <div className="flex items-center">
        <div className="w-full text-center pb-20 bg-orange-500/80">
          <span>
            <p className="pt-6 text-4xl text-orange-50 font-serif mb-4">The Nikee Story</p>
            <p className=" text-orange-50">True beauty is from the inside, true beauties are from our beauty products</p>
          </span>
        </div>
      </div>
      <div className="text-justify py-20">
        <div className="mx-auto w-[60%]">
          <p className="mb-4">
            Nikee is the leading premium beauty platform in Europe. Offering
            more than 130,000 beauty and lifestyle products in online shops, the
            beauty marketplace and more than 2,000 stores, Welly inspires
            customers to live their own kind of beauty by a previously
            unparalleled assortment.
          </p>
          <p>
            The continued expansion of the fast-growing e‑commerce business is
            the focus of the
            <span className="font-bold"> #forwardbeauty</span>. DigitalFirst strategy
            programme. In fiscal year 2019/2020, Welly generated sales of 3.2
            billion euros in the areas of perfumery, decorative cosmetics, skin
            and hair care as well as nutritional supplements and accessories.
            <span className="font-bold"> #letsdobeautiful</span>
          </p>
        </div>
      </div>

      <div className="bg-orange-400/80">
        <div className="flex flex-col md:flex-row py-20 w-3/4 mx-auto">
          {/* Facts and figures */}
          <FactNumber
            icon={"people"}
            number="20,000"
            title="Beauty Experts"
            description="strive to make their customers more beautiful and thus happier"
          />
          <FactNumber
            icon={"revenue"}
            number="3.2"
            title="Billion Euros"
            description="revenue was generated by Douglas in the 2019/20 financial year"
          />
          <FactNumber
            icon={"shop"}
            number="130,000"
            title="Care Products"
            description="because we care about you in online shops, and in stores"
          />
        </div>
      </div>
      <div className="text-center w-2/3 mx-auto my-12">
        <h4 className="font-bold mb-4">Imprint</h4>
        <p>Nikee Inc. Nikee-Street 7-11 40235 Nikeeland</p>
        <p>
          You can reach us by email at: service@Nikee.nekki. <br /> Our
          deliveries go out every Sunday evening so you can get them as early in
          the week as possible
        </p>
      </div>
    </>
  );
};

export default About;
